version: '3'
services:
  proxy:
    image: jwilder/nginx-proxy
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '80:80'

  wordpress:
    image: wordpress:4.9-php7.2-apache
    restart: always
    volumes:
      - ./wordpress:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: wp.local.lcl
      WORDPRESS_DB_HOST: wordpress_mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: admin
      WORDPRESS_DB_NAME: wordpress

  wordpress_mysql:
    build: ./mysql
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: wordpress
    command: >
      --default-authentication-plugin=mysql_native_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
    environment:
      VIRTUAL_HOST: pma.local.lcl
      PMA_HOST: wordpress_mysql
      PMA_USER: root
      PMA_PASSWORD: admin
